// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 KMI Music, Inc.
import {
  SEND_PRESET, // this sends the preset to the device

  SET_MPE_MODE,
  SET_MIDI_DEVICE_CHANNEL,
  SET_MPE_DEVICE_CHANNEL,
  SET_DEVICE_SENSITIVITY,

  SET_NOTE_ON_CURVE_INDEX,
  SET_RELEASE_VELOCITY_ON,
  SET_RELEASE_VELOCITY_CURVE_INDEX,

  SET_ZONE_SPLIT_KEY,
  SET_ZONE_CURVE,

  SET_KEY_AXIS_MODE,
  SET_KEY_AXIS_THRESHOLD,
  SET_KEY_AXIS_GAIN,
  SET_KEY_AXIS_CC,
  SET_KEY_AXIS_OFFSET,
  SET_KEY_AXIS_RELATIVE_START,
  SET_KEY_AXIS_CURVE,
  SET_KEY_AXIS_ZERO_ON_RELEASE,
  SET_KEY_AXIS_INVERT,

  SET_SLIDER_MODE,
  SET_SLIDER_CC,
  SET_SLIDER_ZONE,
  SET_SLIDER_SENSITIVITY,
  SET_LED_MODE,

  SET_PEDAL_MODE,
  SET_PEDAL_CC,
  SET_PEDAL_THRESHOLD,
  SET_PEDAL_ZONE,

  SET_OCTAVE,
  SET_TRANSPOSE,

  SET_PITCH_BEND_MASTER_RANGE,
  SET_PITCH_BEND_MEMBER_RANGE,
  SET_PITCH_BEND_RETURN_MODE,
  SET_PITCH_BEND_RETURN_TIME,
  SET_PITCH_BEND_RETURN_CURVE
} from '../actions/actionTypes'

export default [
  SEND_PRESET, // this sends the preset to the device

  SET_MPE_MODE,
  SET_MIDI_DEVICE_CHANNEL,
  SET_MPE_DEVICE_CHANNEL,
  SET_DEVICE_SENSITIVITY,

  SET_NOTE_ON_CURVE_INDEX,
  SET_RELEASE_VELOCITY_ON,
  SET_RELEASE_VELOCITY_CURVE_INDEX,

  SET_ZONE_SPLIT_KEY,
  SET_ZONE_CURVE,

  SET_KEY_AXIS_MODE,
  SET_KEY_AXIS_THRESHOLD,
  SET_KEY_AXIS_GAIN,
  SET_KEY_AXIS_CC,
  SET_KEY_AXIS_OFFSET,
  SET_KEY_AXIS_RELATIVE_START,
  SET_KEY_AXIS_CURVE,
  SET_KEY_AXIS_ZERO_ON_RELEASE,
  SET_KEY_AXIS_INVERT,

  SET_SLIDER_MODE,
  SET_SLIDER_CC,
  SET_SLIDER_ZONE,
  SET_SLIDER_SENSITIVITY,
  SET_LED_MODE,

  SET_PEDAL_MODE,
  SET_PEDAL_CC,
  SET_PEDAL_THRESHOLD,
  SET_PEDAL_ZONE,

  SET_OCTAVE,
  SET_TRANSPOSE,

  SET_PITCH_BEND_MASTER_RANGE,
  SET_PITCH_BEND_MEMBER_RANGE,
  SET_PITCH_BEND_RETURN_MODE,
  SET_PITCH_BEND_RETURN_TIME,
  SET_PITCH_BEND_RETURN_CURVE
]
